### PR TITLE
Add contribution and contact tokens

### PR DESCRIPTION
**Pull request by rubofvil**

### CODE REVIEW

**Comment by systopia** [comment]
@rubofvil That looks pretty good, great job! I'll look into that when I'm back from a sprint, probably Friday or Tuesday.

**Comment by rubofvil** [comment]
Thank you @systopia . Tell me if you see some error.

Also fix the possibility to uncheck the  store_original_pdf
https://github.com/systopia/de.systopia.donrec/pull/43/commits/7421b741ccaebb7ae41ab2497cd90d2e5aa654b1#diff-51b4ca3cb7f5a2836d3ca923b24d8cb6R132

**Comment by rubofvil** [comment]
Hi @systopia 

We are working in a new version, we will make a new pr with all changes.

Regards.

**Comment by systopia** [comment]
Thanks for the heads up.

**Pull request closed without merging**
