### PR TITLE
Translation adjustment to level the text to CiviCRM fields

### PR DESCRIPTION
**Pull request by CsarRamos**
Translation in CiviCRM:

Captura de pantalla 2020-10-05 a las 16 49 41

Captura de pantalla 2020-10-05 a las 16 50 18

### CODE REVIEW

**Comment by bjendres** [comment]
Thanks @CsarRamos !

**Comment by jensschuppe** [comment]
I guess this will need to be merged into `release/2.0.x` and `master` as well.

**Comment by jensschuppe** [comment]
Will be released with version `2.0` and `2.1`. I don't think there will be another `1.8.x` release.

**Comment by bjendres** [comment]
Released with ``2.0``

**Pull request merged**
