### PR TITLE
Add contact tokens

### PR DESCRIPTION
**Pull request by rubofvil**
I didn't see if is a way to add contact tokens in the template.
This merge give the possibility to add contact tokens in the template.

### CODE REVIEW

**Comment by systopia** [comment]
Hi @rubofvil. Thanks a lot for the PR!

The reason we didn't allow these tokens in the template in the first place is that those values aren't stored in the receipt item. That means the if you later want to create a copy of an existing receipt, it could have different values than the original - and that would violate the regulations for a valid copy. Do you understand this dilemma? Any ideas?

**Comment by rubofvil** [comment]
Thank you @systopia for the explanation
I understand.
Do you think that will be fine if is available the tokens only with the option "Store original *.pdf files"?
In case of select this option(creating the copy) is regenerated the pdf or only is downloaded?

Thank you!

**Comment by systopia** [comment]
I like the idea, but people can turn the option on and off, resulting in a mixed state over time.

How about a switch on the main config page called "allow volatile tokens" and add a help text explaining the problem? Then we could add those tokens only if this setting is enabled. What do you think?

**Comment by rubofvil** [comment]
Great
Later i will work on this, i will also include contribution tokens. Is it ok a new pull request in master?

**Comment by systopia** [comment]
> Later i will work on this, i will also include contribution tokens. Is it ok a new pull request in master?

Sure, however I'll probably pull it into a dev branch first. Thanks!

**Pull request closed without merging**
