### PR TITLE
Fixes CiviCRM 5.60 compatibility issues

### PR DESCRIPTION
**Pull request by bjendres**
Replaces long deprecated and finally abandoned Core code.

See #125

### CODE REVIEW

**Comment by bjendres** [comment]
Here's the current version (might still change until release): [de.systopia.donrec-2.2-dev+af74a9733c6c0e.tar.gz](https://github.com/systopia/de.systopia.donrec/files/11346994/de.systopia.donrec-2.2-dev%2Baf74a9733c6c0e.tar.gz)

**Comment by sleidig** [comment]
This seems to resolve the errors we faced after the last CiviCRM update!

Out of curiosity (trying to understand the depths of CiviCRM development :wink: ): Why did you decide to implement some custom value fetcher instead of using CiviCRM core methods like \Civi\Api4 or CRM_Core_PseudoConstant?

**Comment by bjendres** [comment]
This has been released with ``2.2-beta1``

**Comment by bjendres** [comment]
> Why did you decide to implement some custom value fetcher instead of using CiviCRM core methods like \Civi\Api4 or CRM_Core_PseudoConstant?

This problem is pretty wide-spread in our extensions, so we needed a 100% compatible method call. And the ``CRM_Core_PseudoConstant::getKey`` function is not compatible in *all* cases.

**Pull request merged**
