### PR TITLE
Create receipt for line items of contributions separately, allowing partially receipting of contributions

### LINKED ISSUE #136: Add functionality to create donation receipts for contributions with multiple line items
For example I had an event this year where people could signup and pay the event fee but they could also additionally do another donation. This results in a contribution with two line items, one for the event fee and one for the donation. 
For the line item of the donation we want to create a donation receipt.

I have funding to implement this and a PR fill follow soon.

### PR DESCRIPTION
**Pull request by jaapjansma**
**Before**

Not possible to partially deduct contribution when the contribution has multiple line items (such as a line item for an event fee and an additional donation)

**After**

Donation receipts are calculated based on the information in `civicrm_line_item` If a contribution does not have a line item attached then the information from `civicrm_contribution` is used. 

To enable line item a general setting is introduced. 

Screenshot_20211207_150802

The setting is by default set to no. So by default donation receipts are created based on the information in the contribution. 

Resolves #136

### CODE REVIEW

**Comment by bjendres** [comment]
Thanks. Couldn't we make this configurable? I would like to minimise the impact/risk on people who are already use in the traditional way, and don't need this feature...

**Comment by jaapjansma** [comment]
Do you have a suggestion on how to make this configurable? A setting at the profile page?

**Comment by bjendres** [comment]
> Do you have a suggestion on how to make this configurable? A setting at the profile page?

It doesn't have to be a profile property, just a global setting. This way you'd have to proactively turn it on in order to use this new feature. Maybe with a warning that switching back and forth requires testing.

**Comment by jensschuppe** [comment]
Does this potentially create separate single receipts for each line item of a contribution instead of one receipt per contribution?

**Comment by jaapjansma** [comment]
Yes this creates a line in the `donrec_snapshot` table for each line item.

**Comment by jaapjansma** [comment]
@bjendres I have created a general setting. See this screenshot: 
Screenshot_20211207_150802

**Comment by bjendres** [comment]
Thanks. @jensschuppe, could you have a look please?

**Comment by jensschuppe** [comment]
It hink this will have to be tested thoroughly with different scenarios before merging, the altered query doesn't look as self-explanatory to me as to being able to understand it right away.

**Comment by jaapjansma** [comment]
Hey @jensschuppe thanks, how do you think is needs to be tested? How do we proceed with this?

**Comment by jensschuppe** [comment]
@jaapjansma Unfortunately neither @bjendres nor me will have time for this within the upcoming weeks, maybe not until the end of February. As the extension doesn't have unit test coverage at all, this will have to be tested manually with all combinations of scenarios relevant to your changes (single/bulk receipts, contributions with/without line items, ...) and also legal considerations come to my mind (at least in Germany, there are quite strict regulations regarding purposes of deductable amounts and partly deducting contributions).

Also, detailed documentation on what changes with the new setting might be useful.

If you need this in a timely manner, maybe just go ahead using it with your branch, with proper testing, which you assumedly do anyway.

**Comment by jaapjansma** [comment]
Thanks @jensschuppe I have created a fork of this extension containing this PR. See here for the specific version: https://lab.civicrm.org/partners/civicoop/de.systopia.donrec/-/tree/civicoop

**Comment by jaapjansma** [comment]
This extension has been tested more thoroughly recently and a bug was found which did not include all line items when generating a snapshot. The bug is also fixed in the fork (https://lab.civicrm.org/partners/civicoop/de.systopia.donrec/-/tags/2.1-civicoop-1.1) and in this PR.

**Pull request merged**
